function t190_scrollToTop(){var duration=700;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=0-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t190__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t190__animateScroll(){currentTime+=increment;window.scrollTo(0,t190__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t190__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t190__animateScroll()}
function t229_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t229__list_item a[href=\''+url+'\'], '+'.t229__list_item a[href=\''+url+'/\'], '+'.t229__list_item a[href=\''+pathname+'\'], '+'.t229__list_item a[href=\'/'+pathname+'\'], '+'.t229__list_item a[href=\''+pathname+'/\'], '+'.t229__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t229_checkAnchorLinks(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<980)return;var navLinks=rec.querySelectorAll('.t229__list_item a[href*=\'#\']');navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length){t229_catchScroll(navLinks)}}
function t229_catchScroll(navLinks){navLinks=Array.prototype.slice.call(navLinks);var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;if(Array.isArray(navLinks)){navLinks=navLinks.reverse()}
Array.prototype.forEach.call(navLinks,function(link){var currentSection=t229_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t229_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t229_updateSectionsOffsets(sections)},200));if(typeof jQuery!=='undefined'){$('.t229').bind('displayChanged',function(){t229_updateSectionsOffsets(sections)})}else{var menuEls=document.querySelectorAll('.t229');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t229_updateSectionsOffsets(sections)})})}
setInterval(function(){t229_updateSectionsOffsets(sections)},5000);t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);Array.prototype.forEach.call(navLinks,function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t229_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t229_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t229_getSectionByHref(curlink){if(!curlink)return;var href=curlink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t229_setBg(recid){var menuBlocks=document.querySelectorAll('.t229');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t229_appearMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menuBlocks=rec.querySelectorAll('.t229');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t229_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t229_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t229_slideUpElement(menu,menuHeight,position){var diff=position==='toTop'?0:menuHeight;var diffOpacity=position==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=position==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=position==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(position==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(position==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t229_changeBgOpacityMenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t229');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t390_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var escapeEvent=t390_escClosePopup.bind(this,recId);if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t390_showPopup(recId,escapeEvent);t390_resizePopup(recId);t390__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t390__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t390_closePopup(recId,escapeEvent)});popupCloseBtn.addEventListener('click',function(){t390_closePopup(recId,escapeEvent)});for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup(recId,escapeEvent);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){document.body.classList.add('t-body_popupshowed')},300)}}})}
var curPath=window.location.pathname;var curFullPath=window.location.origin+curPath;var isAndroid=/(android)/i.test(navigator.userAgent);if(isAndroid){var selects='a[href^="#"]:not([href="#"]):not([href^="#price"]):not([href^="#popup"]):not([href^="#prodpopup"]):not([href^="#order"]):not([href^="#!"]),'+'a[href^="'+curPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"]),'+'a[href^="'+curFullPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"])';var selectors=rec.querySelectorAll(selects);for(var i=0;i<selectors.length;i++){selectors[i].addEventListener('click',function(event){var hash=this.hash.trim();if(window.location.hash){setTimeout(function(){window.location.href=hash},50)}})}}
function t390_escClosePopup(recId){if(arguments[1].key==='Escape')t390_closePopup(recId,escapeEvent)}}
function t390_showPopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var documentBody=document.body;popup.style.display='block';setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t390__body_popupshowed');document.addEventListener('keydown',escapeEvent)}
function t390_closePopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupActive=document.querySelector('.t-popup.t-popup_show');if(popup===popupActive){document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t390__body_popupshowed')}
popup.classList.remove('t-popup_show');setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',escapeEvent)}
function t390_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t390_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t397_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var allRecords=document.getElementById('allrecords');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var tildaLazyMode=allRecords?allRecords.getAttribute('data-tilda-lazy'):'';var tabs=rec?rec.querySelectorAll('.t397__tab'):[];if(tildaMode!=='edit'&&tildaMode!=='preview'){t397_scrollToTabs(recid)}
Array.prototype.forEach.call(tabs,function(tab,i){tab.setAttribute('data-tab-index',i);tab.addEventListener('click',function(e){var targetTab=e.target.closest('.t397__tab');if(targetTab&&targetTab.classList.contains('t397__tab_active')&&!e.isTrusted)return;var activeTab=rec.querySelector('.t397__tab_active');if(activeTab)activeTab.classList.remove('t397__tab_active');targetTab.classList.add('t397__tab_active');t397_removeUrl();var tabNumber=i+1;if(tildaMode!=='edit'&&tildaMode!=='preview'&&tabNumber&&typeof history.replaceState!=='undefined'){try{window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}catch(err){}}
t397_alltabs_updateContent(recid);t397_updateSelect(recid);var hookBlocks=targetTab.getAttribute('data-tab-rec-ids').split(',');var event=document.createEvent('Event');event.initEvent('displayChanged',!0,!0);hookBlocks.forEach(function(curRecid){var currentRec=document.getElementById('rec'+curRecid);if(!currentRec)return;var currentRecChildren=currentRec.querySelectorAll('.t-feed, .t-store, .t-store__product-snippet, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t448, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t569, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t889, .t902, .t912, .t923, .t937, .t959, .t979, .t982, .t983, .t989, .t994');Array.prototype.forEach.call(currentRecChildren,function(child){child.dispatchEvent(event)});var displayChangedBlock=currentRec.querySelector('[data-display-changed="true"]');if(displayChangedBlock)displayChangedBlock.dispatchEvent(event)});var galaxyEffectBlocks=document.querySelectorAll('.t826');Array.prototype.forEach.call(galaxyEffectBlocks,function(galaxyEffectBlock){galaxyEffectBlock.dispatchEvent(event)});t397_startUpdateLazyLoad(targetTab);if(window.lazy==='y'||tildaLazyMode==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})});if(tabs.length){t397_alltabs_updateContent(recid);t397_updateContentBySelect(recid);var bgColor=rec?rec.style.backgroundColor:'#ffffff';var bgColorTargets=rec.querySelectorAll('.t397__select, .t397__firefoxfix');Array.prototype.forEach.call(bgColorTargets,function(target){target.style.background=bgColor})}
document.addEventListener('click',function(e){if(e.target.closest('[href*="#!/tab/'+recid+'"]')){var currentLink=e.target.closest('[href*="#!/tab/'+recid+'"]');var hash=currentLink.hash;t397_scrollToTabs(recid,hash)}})}
function t397_alltabs_updateContent(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var tabs=Array.prototype.slice.call(rec.querySelectorAll('.t397__tab:not(.t397__tab_active)'));var activeTab=rec.querySelector('.t397__tab_active');var select=rec.querySelector('.t397__select');if(!activeTab)return;var hookBlocks=activeTab.getAttribute('data-tab-rec-ids').split(',');var noActive=[];Array.prototype.forEach.call(tabs,function(tab){if(tab!==activeTab){var noActiveHooks=tab.getAttribute('data-tab-rec-ids').split(',');noActiveHooks.forEach(function(hook){if(noActive.indexOf(hook)===-1&&hookBlocks.indexOf(hook)===-1)noActive.push(hook)})}});if(t397_checkVisibillityEl(activeTab)||t397_checkVisibillityEl(select)){hookBlocks.forEach(function(hook){if(!hook)return;var hookEl=document.getElementById('rec'+hook);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';if(hookEl)hookEl.classList.remove('t397__off');if(hookEl)hookEl.style.opacity='';t397_updateTabsByHook(hookElRecordType,hookEl,hook,recid)})}else{hookBlocks.forEach(function(hook){var hookEl=document.getElementById('rec'+hook);if(hookEl)hookEl.setAttribute('data-animationappear','off');if(hookEl)hookEl.classList.add('t397__off')})}
noActive.forEach(function(noActiveID){if(!noActiveID)return;var hookEl=document.getElementById('rec'+noActiveID);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';if(hookEl)hookEl.setAttribute('data-connect-with-tab','yes');if(hookEl)hookEl.setAttribute('data-animationappear','off');if(hookEl)hookEl.classList.add('t397__off');t397_updateTabsByHook(hookElRecordType,hookEl,noActiveID,recid)});var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(scrollHeight-window.innerHeight<window.pageYOffset){window.scrollTo(0,0)}}
function t397_updateTabsByHook(hookElRecordType,hookEl,currentID,recid){var hookElTab;switch(hookElRecordType){case '395':if(window.t395_alltabs_updateContent&&window.t395_updateSelect&&recid!==currentID){window.t395_alltabs_updateContent(currentID);window.t395_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t395__tab'):null;if(hookElTab)hookElTab.click()}
break;case '397':if(recid!==currentID){t397_alltabs_updateContent(currentID);t397_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t397__tab'):null;if(hookElTab)hookElTab.click()}
break}}
function t397_checkVisibillityEl(el){return!!(el&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length))}
function t397_updateContentBySelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var select=rec.querySelector('.t397__select');if(select){select.addEventListener('change',function(){var tabIndex=rec.querySelector('.t397__tab[data-tab-rec-ids=\''+select.value+'\'][data-tab-index="'+select.selectedIndex+'"]');if(tabIndex)tabIndex.click()})}}
function t397_updateSelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var activeTab=rec.querySelector('.t397__tab_active');var currentTabHooks=activeTab?activeTab.getAttribute('data-tab-index'):'';var select=rec.querySelector('.t397__select');if(select)select.selectedIndex=currentTabHooks}
function t397_startUpdateLazyLoad(el){var hookBlocks=el?el.getAttribute('data-tab-rec-ids').split(','):[];hookBlocks.forEach(function(hook){var rec=document.getElementById('rec'+hook);if(!rec)return;var videos=rec.querySelectorAll('.t-video-lazyload');if(videos.length){t397_updateVideoLazyLoad(videos)}})}
function t397_updateVideoLazyLoad(videos){setTimeout(function(){Array.prototype.forEach.call(videos,function(video){if(!video.classList.contains('t-video__isload')){var heightAttribute=video.getAttribute('data-videolazy-height');var height=heightAttribute?heightAttribute:'100%';if(height.indexOf('vh')!==-1)height='100%';var videoID=video.getAttribute('data-videolazy-id');videoID=videoID?videoID.trim():'';var blockID=video.getAttribute('data-blocklazy-id');var twoIdAttr=video.getAttribute('data-videolazy-two-id');var videoTwoID=twoIdAttr?'_'+twoIdAttr+'_':'';if(video.getAttribute('data-videolazy-type')==='youtube'){var oldIframe=video.querySelector('iframe');if(oldIframe&&oldIframe.parentNode)oldIframe.parentNode.removeChild(oldIframe);var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+videoTwoID+blockID;iframe.width='100%';iframe.height=height;iframe.src='https://www.youtube.com/embed/'+videoID+'?rel=0&fmt=18&html5=1&showinfo=0';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');video.insertAdjacentElement('beforeend',iframe)}}
video.classList.add('t-video__isload')})},2)}
function t397_scrollToTabs(recid,hash){var rec=document.getElementById('rec'+recid);var curUrl=hash||window.location.href;var tabIndexNumber=curUrl.indexOf('#!/tab/');if(tabIndexNumber===-1)return!1;var tabIndexNumberStart=curUrl.indexOf('tab/');var firstOptionSelect=rec?rec.querySelector('.t397__wrapper_mobile .t397__select option'):null;if(firstOptionSelect)firstOptionSelect.selected=!1;var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(tabRec!==recid)return!1;var tabBlock=rec?rec.querySelector('.t397'):null;var tabNumber=parseInt(curUrl.slice(tabIndexNumberStart+4+recid.length+1),10);var tabs=rec.querySelectorAll('.t397__tab');Array.prototype.forEach.call(tabs,function(tab,i){if(i===tabNumber-1){tab.click();tab.classList.add('t397__tab_active')}else{tab.classList.remove('t397__tab_active')}});var tabsMob=rec.querySelectorAll('.t397__wrapper_mobile .t397__select option');var activeTabMob=tabsMob.length?tabsMob[tabNumber-1]:null;if(activeTabMob)activeTabMob.selected=!0;var targetOffset=tabBlock.getBoundingClientRect().top+window.pageYOffset;var target=window.innerWidth>960?targetOffset-200:targetOffset-100;if(target<0)target=0;t397_scrollToEl(target)}
function t397_scrollToEl(elTopPos){if(elTopPos===window.pageYOffset)return!1;var duration=300;var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=10*(elTopPos||window.pageYOffset)/duration;var timer=setInterval(function(){if(cashedDiff>elTopPos){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>elTopPos&&window.pageYOffset<=elTopPos||cashedDiff<=elTopPos&&window.pageYOffset>=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10);var timer2=setTimeout(function(){clearInterval(timer);document.body.removeAttribute('data-scrollable');clearTimeout(timer2)},duration*2)}
function t397_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(indexToRemove===-1){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!==-1){if(typeof history.replaceState!='undefined'){try{window.history.replaceState('','',curUrl)}catch(err){}}}}
function t409_unifyHeights(recid){if(window.innerWidth<=960)return;var rec=document.getElementById('rec'+recid);if(!rec)return;var image=rec.querySelector('.t409__img');if(!image)return;image.onload=function(){var imageWidth=parseInt(image.width,10);var imageWrapperWidth=parseInt(window.getComputedStyle(rec.querySelector('.t409__imgwrapper')).maxWidth,10);var margin=imageWrapperWidth-imageWidth;image.style.marginLeft=margin+'px'}}
function t451_initMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var burgerList=rec.querySelectorAll('.t451__burger');var menu=rec.querySelector('.t451m');var menuBlock=rec.querySelector('.t451');var overlay=rec.querySelector('.t451m__overlay');var links=rec.querySelectorAll('.t-menu__link-item');Array.prototype.forEach.call(burgerList,function(burger){burger.addEventListener('click',function(e){e.preventDefault();t451_closeMenu(menu,overlay);t451_showMenu(menu,overlay);t451_checkSize(menu)})});if(menu){menu.click(function(e){t451_closeMenu(menu,overlay);t451_showMenu(menu,overlay);t451_checkSize(menu);e.preventDefault()})}
if(menuBlock){menuBlock.addEventListener('clickedAnchorInTooltipMenu',function(){t451_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(links,function(link){if(window.isMobile&&link.classList.contains('t451__link-item_submenu')){link.addEventListener('click',function(){t451_checkSize(menu);setTimeout(function(){t451_checkSize(menu)})})}
if(link.classList.contains('t966__tm-link')){link.addEventListener('click',function(){setTimeout(function(){t451_checkSize(menu)},305)})}
if(link.classList.contains('t978__tm-link')){link.addEventListener('click',function(){var linksElements=rec.querySelectorAll('.t978__menu-link');Array.prototype.forEach.call(linksElements,function(element){element.addEventListener('click',function(){t451_checkSize(menu)})})})}});window.addEventListener('resize',function(){t451_checkSize(menu)});var navLinks=rec.querySelectorAll('.t451 a.t-menu__link-item[href*="#"], .t451 a.t-menusub__link-item[href*="#"]');navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length>0){t451_catchScroll(navLinks)}
t451_highlight(recid);document.addEventListener('click',function(e){if(e.target.closest('.t451m__overlay, .t451m__close, a[href*="#"]:not(.tooltipstered):not(.t794__tm-link):not(.t978__tm-link):not(.t966__tm-link)')){t451_closeMenu(menu,overlay)}});document.addEventListener('keydown',function(e){if(e.keyCode===27){t451_closeMenu(menu,overlay)}})}
function t451_showMenu(menu,overlay){if(!menu)return;document.body.classList.add('t451__body_menushowed');menu.classList.add('t451m__menu_show');if(overlay)overlay.classList.add('t451m__menu_show')}
function t451_closeMenu(menu,overlay){document.body.classList.remove('t451__body_menushowed');if(menu)menu.classList.remove('t451m__menu_show');if(overlay)overlay.classList.remove('t451m__menu_show')}
function t451_checkSize(menu){if(!menu)return;var menuTop=menu.querySelector('.t451m__top');var menuRight=menu.querySelector('.t451m__rightside');var menuContainer=menu.querySelector('.t451m__container');var menuTopHeight=menuTop?menuTop.offsetHeight:0;var menuRightHeight=menuRight?menuRight.offsetHeight:0;var windowPadding=80;if(menuTopHeight+menuRightHeight+windowPadding>window.innerHeight){menu.classList.add('t451m__overflowed');if(menuContainer)menuContainer.style.height='auto'}else{menu.classList.remove('t451m__overflowed');if(menuContainer)menuContainer.style.height=''}}
function t451_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t451m__menu a[href=\''+url+'\'], '+'.t451m__menu a[href=\''+url+'/\'], '+'.t451m__menu a[href=\''+pathname+'\'], '+'.t451m__menu a[href=\'/'+pathname+'\'], '+'.t451m__menu a[href=\''+pathname+'/\'], '+'.t451m__menu a[href=\'/'+pathname+'/\']'+(hash?', .t451m__menu a[href=\''+hash+'\']':'')+(hash?', .t451m__menu a[href=\'/'+hash+'\']':'')+(hash?', .t451m__menu a[href=\''+hash+'/\']':'')+(hash?', .t451m__menu a[href=\'/'+hash+'/\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t451m__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t451_changeBgOpacityMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t451__container__bg');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity2');var menuShadow=menu.getAttribute('data-menu-shadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t451_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t451__panel'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';if(burgerAppearOffset)burgerAppearOffset=t451_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t451__beforeready')){burger.classList.remove('t451__beforeready')}}else{burger.classList.add('t451__beforeready')}}
function t451_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string,10)/100)))}
return parseInt(string,10)}
function t451_catchScroll(navLinks){navLinks=Array.prototype.slice.call(navLinks);var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;navLinks=navLinks.reverse();navLinks.forEach(function(link){var currentSection=t451_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t451_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t451_updateSectionsOffsets(sections)},200));if(typeof jQuery!=='undefined'){$('.t451').bind('displayChanged',function(){t451_updateSectionsOffsets(sections)})}else{var menuEls=document.querySelectorAll('.t451');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t451_updateSectionsOffsets(sections)})})}
setInterval(function(){t451_updateSectionsOffsets(sections)},5000);t451_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);navLinks.forEach(function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t451_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t451_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t451_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t451_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t451_getSectionByHref(curlink){if(!curlink)return;var href=curlink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t451_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t604_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;t604_imageHeight(recid);t604_arrowWidth(recid);t604_show(recid);t604_hide(recid);window.addEventListener('resize',t_throttle(function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)}));if(typeof jQuery!=='undefined'){$(rec).find('.t604').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}else{var currentBlock=rec.querySelector('.t604');if(currentBlock){currentBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}}}
function t604_show(recid){var rec=document.getElementById('rec'+recid);var playBtns=rec.querySelectorAll('.t604__play');Array.prototype.forEach.call(playBtns,function(play){play.addEventListener('click',function(){var parent=play.parentElement;var videoBg=parent?parent.querySelector('.t-slds__bgimg'):null;if(videoBg)videoBg.style.opacity='0';var sliderVideo=play.getAttribute('data-slider-video-type');var url=play.getAttribute('data-slider-video-url');var nextEl=play.nextElementSibling;if(nextEl)nextEl.style.zIndex='3';var iframe;switch(sliderVideo){case 'youtube':iframe=document.createElement('iframe');iframe.classList.add('t604__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://www.youtube.com/embed/'+url+'?autoplay=1&enablejsapi=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay');if(nextEl)nextEl.innerHTML='';if(nextEl)nextEl.appendChild(iframe);break;case 'vimeo':var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(url);var id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;iframe=document.createElement('iframe');iframe.classList.add('t604__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://player.vimeo.com/video/'+id+hash+'?autoplay=1&amp;api=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');if(nextEl)nextEl.innerHTML='';if(nextEl)nextEl.appendChild(iframe);break}})})}
function t604_hide(recid){var rec=document.getElementById('rec'+recid);var frames=rec.querySelectorAll('.t604__frame');rec.addEventListener('updateSlider',function(){Array.prototype.forEach.call(frames,function(frame){frame.innerHTML='';frame.style.zIndex=''})})}
function t604_imageHeight(recid){var rec=document.getElementById('rec'+recid);var images=rec.querySelectorAll('.t604__separator');Array.prototype.forEach.call(images,function(image){var imgHeight=image.getAttribute('data-slider-image-height');var imgWidth=image.getAttribute('data-slider-image-width');var imgRatio=imgHeight/imgWidth;var imgPadding=imgRatio*100;image.style.paddingBottom=imgPadding+'%'})}
function t604_arrowWidth(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var arrows=rec.querySelectorAll('.t-slds__arrow_wrapper');var slide=rec.querySelector('.t-slds__wrapper');var slideWidth=slide?slide.offsetWidth:0;var arrowWidth=window.innerWidth-slideWidth;Array.prototype.forEach.call(arrows,function(arrow){arrow.style.width=window.innerWidth>960?(arrowWidth/2)+'px':''})}
function t609_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t609');if(!container)return;var descriptions=rec.querySelectorAll('.t609__descr');var maxHeight=0;for(var i=0;i<descriptions.length;i++){descriptions[i].style.height=''}
for(var i=0;i<descriptions.length;i++){var description=descriptions[i];var descriptionStyle=getComputedStyle(description,null);var descriptionPaddingTop=parseInt(descriptionStyle.paddingTop)||0;var descriptionPaddingBottom=parseInt(descriptionStyle.paddingBottom)||0;var descriptionHeight=description.clientHeight-(descriptionPaddingTop+descriptionPaddingBottom);if(descriptionHeight>maxHeight)maxHeight=descriptionHeight}
if(window.innerWidth>=960){for(var i=0;i<descriptions.length;i++){descriptions[i].style.height=maxHeight+'px'}}else{for(var i=0;i<descriptions.length;i++){descriptions[i].style.height=''}}}
function t609_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t609');if(!container)return;var bgImages=rec.querySelectorAll('.t609__bgimg');for(var i=0;i<bgImages.length;i++){var bgImage=bgImages[i];var bgImageWidth=bgImage.getAttribute('data-image-width');var bgImageHeight=bgImage.getAttribute('data-image-height');var ratio=bgImageHeight/bgImageWidth;var paddingBottom=ratio*100;bgImage.style.paddingBottom=paddingBottom+'%'}}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var playBtns=rec.querySelectorAll('.t670__play');Array.prototype.forEach.call(playBtns,function(play){play.addEventListener('click',function(){var videoType=play.getAttribute('data-slider-video-type');var url;var nextEl;var prevEl;var iframe;var video;var source;switch(videoType){case 'youtube':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;if(nextEl){iframe=document.createElement('iframe');iframe.classList.add('t670__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://www.youtube.com/embed/'+url+'?autoplay=1&enablejsapi=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay');nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',iframe)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break;case 'vimeo':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(url);var id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;if(nextEl){iframe=document.createElement('iframe');iframe.classList.add('t670__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://player.vimeo.com/video/'+id+hash+'&amp;api=1';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay; fullscreen');nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',iframe)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break;case 'mp4':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;if(nextEl){video=document.createElement('video');source=document.createElement('source');video.insertAdjacentElement('beforeend',source);video.classList.add('t670__video');video.controls=!0;source.src=url;nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',video)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break}
if(nextEl)nextEl.style.zIndex='3'})})}
function t670_hide(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var elBody=rec.querySelector('.t670__frame');rec.addEventListener('updateSlider',function(){if(elBody)elBody.innerHTML='';if(elBody)elBody.style.zIndex=''})}
function t670_imageHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var images=rec.querySelectorAll('.t670__separator');Array.prototype.forEach.call(images,function(img){var width=img.getAttribute('data-slider-image-width')||0;var height=img.getAttribute('data-slider-image-height')||0;var ratio=height/width;var padding=ratio*100;img.style.paddingBottom=padding+'%'})}
function t698_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t698__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t698__fadeOut(tildaLabel)}},300)}else{t698__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t698__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t698__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t698__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t698__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t698__animateScroll(){currentTime+=increment;window.scrollTo(0,t698__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t698__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t698__animateScroll()}
function t698_fixcontentheight(recId){var rec=document.getElementById('rec'+recId);var cover=rec.querySelector('.t-cover');var coverFilter=rec.querySelector('.t-cover__filter');var coverCarrier=rec.querySelector('.t-cover__carrier');var coverWrapper=rec.querySelector('.t-cover__wrapper');var coverContainer=rec.querySelector('.t-cover__container');var coverStyle=getComputedStyle(cover,null);var coverPaddingTop=parseInt(coverStyle.paddingTop)||0;var coverPaddingBottom=parseInt(coverStyle.paddingBottom)||0;var coverHeight=cover.clientHeight-(coverPaddingTop+coverPaddingBottom);var hookContent=rec.querySelector('div[data-hook-content]');var hookContentHeight=hookContent.offsetHeight;if(hookContentHeight>300&&coverHeight<hookContentHeight){var newHookContentHeight=hookContentHeight+120;if(newHookContentHeight>1000)newHookContentHeight+=100;console.log('auto correct cover height: '+newHookContentHeight);cover.style.height=newHookContentHeight+'px';if(coverFilter)coverFilter.style.height=newHookContentHeight+'px';if(coverCarrier)coverCarrier.style.height=newHookContentHeight+'px';if(coverWrapper)coverWrapper.style.height=newHookContentHeight+'px';if(coverContainer)coverContainer.style.height=newHookContentHeight+'px';if(window.isMobile===!1){setTimeout(function(){if(coverCarrier.querySelector('iframe')){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(coverCarrier,newHookContentHeight+'px')}},2000)}}}
function t776__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t776_initPopup(recid);t776__hoverZoom_init(recid);t776__updateLazyLoad(recid);t776__alignButtons_init(recid);if(typeof t_store_addProductQuantityEvents!=='undefined'){t776_initProductQuantity(recid)}
$('body').trigger('twishlist_addbtn')},500)}
function t776_initProductQuantity(recid){var el=$('#rec'+recid);var productList=el.find(".t776__col, .t776__product-full");productList.each(function(i,product){t_store_addProductQuantityEvents($(product))})}
function t776__showMore(recid){var el=$('#rec'+recid).find(".t776");var showmore=el.find('.t776__showmore');var cards_count=parseInt(el.attr('data-show-count'),10);if(cards_count>0){if(showmore.text()===''){showmore.find('td').text(t776__dict('loadmore'))}
showmore.show();el.find('.t776__col').hide();var cards_size=el.find('.t776__col').size();var x=cards_count;var y=cards_count;t776__showSeparator(el,x);el.find('.t776__col:lt('+x+')').show();var currentColDisplayProp=el.find('.t776__col:lt('+x+')').css('display');window.addEventListener('resize',function(){var col=el.find('.t776__col:lt('+x+')');col.each(function(){this.style.display=''});currentColDisplayProp=el.find('.t776__col:lt('+x+')').css('display');col.css('display',currentColDisplayProp==='none'?'inline-block':currentColDisplayProp)});showmore.click(function(){x=(x+y<=cards_size)?x+y:cards_size;el.find('.t776__col:lt('+x+')').css('display',currentColDisplayProp==='none'?'inline-block':currentColDisplayProp);if(x==cards_size){showmore.hide()}
t776__showSeparator(el,x);if($('#rec'+recid).find('[data-buttons-v-align]')[0]){t776__alignButtons(recid)}
if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t776__showSeparator(el,x){el.find('.t776__separator_number').addClass('t776__separator_hide');el.find('.t776__separator_hide').each(function(){if($(this).attr('data-product-separator-number')<=x){$(this).removeClass('t776__separator_hide')}})}
function t776__dict(msg){var dict=[];dict.loadmore={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var lang=window.browserLang;if(typeof dict[msg]!=='undefined'){if(typeof dict[msg][lang]!=='undefined'&&dict[msg][lang]!=''){return dict[msg][lang]}else{return dict[msg].EN}}
return 'Text not found "'+msg+'"'}
function t776__alignButtons_init(recid){var el=$('#rec'+recid);if(el.find('[data-buttons-v-align]')[0]){try{t776__alignButtons(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t776__alignButtons(recid)}));el.find('.t776').bind('displayChanged',function(){t776__alignButtons(recid)});if($isMobile){$(window).on('orientationchange',function(){t776__alignButtons(recid)})}}catch(e){console.log('buttons-v-align error: '+e.message)}}}
function t776__alignButtons(recid){var rec=$('#rec'+recid);var wrappers=rec.find('.t776__textwrapper');var maxHeight=0;var itemsInRow=rec.find('.t-container').attr('data-blocks-per-row')*1;var mobileView=$(window).width()<=480;var tableView=$(window).width()<=960&&$(window).width()>480;var mobileOneRow=$(window).width()<=960&&rec.find('.t776__container_mobile-flex')[0]?true:!1;var mobileTwoItemsInRow=$(window).width()<=480&&rec.find('.t776 .mobile-two-columns')[0]?true:!1;if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var i=1;var wrappersInRow=[];$.each(wrappers,function(key,element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
$.each(wrappersInRow,function(key,wrapper){wrapper.style.height=maxHeight+'px'});if(i===itemsInRow){i=0;maxHeight=0;wrappersInRow=[]}
i++}})}
function t776__hoverZoom_init(recid){if(isMobile){return}
var rec=$('#rec'+recid);try{if(rec.find('[data-hover-zoom]')[0]){if(!jQuery.cachedZoomScript){jQuery.cachedZoomScript=function(url){var options={dataType:'script',cache:!0,url:url};return jQuery.ajax(options)}}
$.cachedZoomScript('https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js').done(function(script,textStatus){if(textStatus=='success'){setTimeout(function(){t_hoverZoom_init(recid)},500)}else{console.log('Upload script error: '+textStatus)}})}}catch(e){console.log('Zoom image init error: '+e.message)}}
function t776__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t776__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t776_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').each(function(e){var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');$(".r").find('a[href$="#!/tproduct/'+recid+'-'+lid_prod+'"]').click(function(e){if(rec.find('[data-product-lid='+lid_prod+']').length){rec.find('[data-product-lid='+lid_prod+'] [href^="#prodpopup"]').triggerHandler('click')}})});rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t776__product-'+lid_prod+'')})});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();if($(e.target).hasClass('t1002__addBtn')||$(e.target).parents().hasClass('t1002__addBtn')){return}
t776_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]');el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t776_updateSlider(recid+' #t776__product-'+lid_prod+'');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});if($('#record'+recid).length==0){t776_checkUrl(recid)}
t776_copyTypography(recid)}
function t776_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/')}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t776_updateSlider(recid){var el=$('#rec'+recid);t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t776_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);$('body').addClass('t-body_popupshowed');$('body').trigger('twishlist_addbtn');el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t776_closePopup()}});el.find('.t-popup__close, .t776__close-text').click(function(e){t776_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t776_closePopup()}});if(window.isSafari){setTimeout(function(){el.find('.t-popup').scrollTop(1)})}}
function t776_closePopup(){$('body').removeClass('t-body_popupshowed');$('body').trigger('twishlist_addbtn');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/')}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t776_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t776_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t776__title').attr('style');var descrStyle=rec.find('.t776__descr').attr('style');rec.find('.t-popup .t776__title').attr("style",t776_removeSizeStyles(titleStyle));rec.find('.t-popup .t776__descr, .t-popup .t776__text').attr("style",t776_removeSizeStyles(descrStyle))}